spring.application.name=hackathon-platform

spring.datasource.url=jdbc:mysql://localhost:8889/hackathon_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=changeMeToALongRandomSecretKeyAtLeast256BitsForHS256Algorithm
jwt.expiration=86400000

# Dossier où seront stockés les fichiers uploadés (créé automatiquement s'il n'existe pas)
app.upload.dir=uploads/projects

# Limites de taille (Spring Boot bloque au-delà par défaut à 1MB, on l'augmente)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB